#**Numpy & Functions**

In [1]:
def add(a,b):
  return a+b

In [2]:
#function with parameters
x = 10
y = 20
res= add(x,y)
print("sum =", res)


sum = 30


In [7]:
#funtion with no parameter

def welcome():
  print("Welcome to Python Lab")
welcome()



Welcome to Python Lab


In [8]:
#to print square using sq function
def sq(n):
  return n*n
print(sq(5))

25


In [12]:
#taking input from user
import numpy as np
n=int(input("How many numbers?"))
number = []
for i in range(n):
  x = int(input("Enter number:"))
  number.append(x)
arr = np.array(number)
print("Numpy Array:", arr)
print("Array type:", type(arr))
print("Numpy Array type", arr.dtype)
print("Numpy Array type", arr.shape)
print("Numpy Array dimension", arr.ndim)


How many numbers?3
Enter number:4
Enter number:5
Enter number:6
Numpy Array: [4 5 6]
Array type: <class 'numpy.ndarray'>
Numpy Array type int64
Numpy Array type (3,)
Numpy Array dimension 1


In [13]:
#how to create a function of numpy array using values from user
def create_array(n):
  number= []
  for i in range(n):
    x = int(input("Enter number:"))
    number.append(x)
  return np.array(number)

In [14]:
#storing numpy array into the original array from user and returning it
n=int(input("How many numbers?"))
arr = create_array(n)
print("Numpy Array:", arr)
print("Array type:", type(arr))
print("Numpy Array type", arr.dtype)
print("Numpy Array type", arr.shape)
print("Numpy Array dimension", arr.ndim)


How many numbers?3
Enter number:2
Enter number:3
Enter number:4
Numpy Array: [2 3 4]
Array type: <class 'numpy.ndarray'>
Numpy Array type int64
Numpy Array type (3,)
Numpy Array dimension 1


#**Default Arguments**

In [24]:
def printInfo(name,age):
  print("Name:", name)
  print("Age:", age)

In [25]:
def printInfo(name, age=21):
  print("Name:", name)
  print("Age:", age)

In [26]:
printInfo("Raj", 25)
printInfo("Varun")

Name: Raj
Age: 25
Name: Varun
Age: 21


#**Required Arguments**
order matters


In [27]:
def printInfo(name,age):
  print("Name:", name)
  print("Age:", age)

In [32]:
printInfo("Raj", 21)

Name: Raj
Age: 21


#**Keyword Argument**

order does not matter

In [ ]:
def printInfo(name,age):
  print("Name:", name)
  print("Age:", age)

In [34]:
printInfo(age=21, name = "Raj" )

Name: Raj
Age: 21


#**Variable Length Argument**

it is compulsory to pass two arguments

In [60]:
def add(a,b):
  print(a+b)

In [61]:
add(10, 20)
#add(10,20,30,40,50) can't add more elements than mentioned it will give error

30


In [100]:
def add(*num):
  total = 0
  for n in num:
    total+= n
  print(total)

In [99]:
add(10,20)
add(10,20,30,40,50)

30
150


#**Variable length arguments**(**kwargs)

In [71]:
def student(**details):
  print(details)
student(name= "Raj", age=21, course= "python")

{'name': 'Raj', 'age': 21, 'course': 'python'}


In [79]:
def calculate(a,b):
  return a+b, a-b, a*b

s, d, m = calculate(10,5)
print("Sum", s)
print("Difference",d)
print("Multiplication",m)

Sum 15
Difference 5
Multiplication 50


#**Reshaping Array**

In [92]:
data= np.arange(1,13)
a = data.reshape(3,4)
b = data.reshape(4,3)
c = data.reshape(2,-1)
print(f'1D Array:\n{data}')
print(f'3x4:\n{a}')
print(f'4x3:\n{b}')
print(f'2xinfer:\n{c}')
print(f'A shape\n{a.shape}')
print(f'B shape\n{b.shape}')
print(f'C shape\n{c.shape}')

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2xinfer:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
A shape
(3, 4)
B shape
(4, 3)
C shape
(2, 6)


**Write a function to create an array by taking input by user. Reshape the array into numpy array 6x2, 3x1 and 5x-1 matrix and if errors comes please explain the error**

In [93]:
import numpy as np

def create_array():
    n = int(input("Enter number of elements: "))

    arr = []

    for i in range(n):
        value = int(input(f"Enter element {i+1}: "))
        arr.append(value)

    return np.array(arr)


arr = create_array()

print("Original Array:", arr)

# Reshape into 6 x 2
try:
    print("6 x 2 Matrix:")
    print(arr.reshape(6, 2))
except ValueError:
    print("Error: 6 x 2 needs exactly 12 elements.")

# Reshape into 3 x 1
try:
    print("3 x 1 Matrix:")
    print(arr.reshape(3, 1))
except ValueError:
    print("Error: 3 x 1 needs exactly 3 elements.")

# Reshape into 5 x -1
try:
    print("5 x -1 Matrix:")
    print(arr.reshape(5, -1))
except ValueError:
    print("Error: Number of elements must be divisible by 5.")

Enter number of elements: 3
Enter element 1: 3
Enter element 2: 4
Enter element 3: 5
Original Array: [3 4 5]
6 x 2 Matrix:
Error: 6 x 2 needs exactly 12 elements.
3 x 1 Matrix:
[[3]
 [4]
 [5]]
5 x -1 Matrix:
Error: Number of elements must be divisible by 5.


#**flatten() and ravel()**

In [97]:
data = np.array([[1,2,3], [4,5,6]])
print("Data shape:", data.ndim)

flat1 = data.flatten()
print("Data shape:", flat1.ndim)

flat2 = data.ravel()
print("Data shape:", flat1.ndim)


Data shape: 2
Data shape: 1
Data shape: 1


#np.concatenate
#np.vstack()
#np.hstack()

In [103]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f'concatenate\n:{np.concatenate((a,b))}')
print(f'vstack:\n{np.vstack((a,b))}')
print(f'hstack\n:{np.hstack((a,b))}')


concatenate
:[1 2 3 4 5 6]
vstack:
[[1 2 3]
 [4 5 6]]
hstack
:[1 2 3 4 5 6]


#**Vectorization**

In [124]:

data = np.array([10,20,30,40,50])
result = []
for x in data:
  result.append(x*2)
print(f'loop array:,{result}')

loop array:,[np.int64(20), np.int64(40), np.int64(60), np.int64(80), np.int64(100)]


In [113]:
vec_result = data*2
print(f'Vec array: {vec_result}')

Vec array: [ 20  40  60  80 100]


In [116]:
#Using function using user imports
a= np.array([10,20,30])
b= np.array([2,4,5])
print(f'Addition: {a+b}')
print(f'Subtraction: {a-b}')
print(f'Multiplication: {a*b}')
print(f'Division {a/b}')

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division [5. 5. 6.]


In [118]:
marks= np.array([50, 60, 70, 80, 90])
print(f'Add 5: {marks+5}')
print(f'Sub 10: {marks-10}')
print(f'Double: {marks*2}')
print(f'Half: {marks/2}')


Add 5: [55 65 75 85 95]
Sub 10: [40 50 60 70 80]
Double: [100 120 140 160 180]
Half: [25. 30. 35. 40. 45.]


In [122]:
print(f'square: {np.square(marks)} ')

square: [2500 3600 4900 6400 8100] 


In [123]:
print(f'sqrt: {np.sqrt(marks)} ')

sqrt: [7.07106781 7.74596669 8.36660027 8.94427191 9.48683298] 


#**Broadcasting**

arithmetic operations on different shapes

In [125]:
arr = np.array([1,2,3])
res = arr+1
print(res)

[2 3 4]


In [126]:
#Broadcasting from 1D to 2D Array
a = np.array([2,4,6])
b = np.array([[1,3,5], [7,9,11]])
res = a+b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


#**Broadcasting in conditional operations**

In [128]:

a = np.array([12,24,35,45,60,72])
b = np.array(["Adult", "Minor"])
res = np.where(a>18, b[0], b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


#**Broadcasting for Matrix Multiplication**

In [133]:
m = np.array([[1,2], [3,4]])
v = np.array([10,20])
res = m*v
print(res)

[[10 40]
 [30 80]]
