In [8]:
num = int(input("enter an integer"))
print(type(num))

enter an integer5
<class 'int'>


In [9]:
for i in range(1,11):
  print(f'{num}x{i}={num*i}')

5x1=5
5x2=10
5x3=15
5x4=20
5x5=25
5x6=30
5x7=35
5x8=40
5x9=45
5x10=50


In [11]:
a = float(input("enter first number"))
b= float(input("enter second number"))
print(f'sum of {a} and {b} is {a+b}')
print(f'subtraction:{a-b}')
print(f'multiplication:{a*b}')
print(f'division:{a/b}')
print(f'floor:{a//b}')
print(f'modulus:{a%b}')
print(f'exponent:{a**b}')

enter first number17.9
enter second number4.5
sum of 17.9 and 4.5 is 22.4
subtraction:13.399999999999999
multiplication:80.55
division:3.9777777777777774
floor:3.0
modulus:4.399999999999999
exponent:434348.8134104658


In [13]:
#looping
nums=[12,14,19,10,20]
tot=0
for x in nums:
  tot=tot+x
print(f'the total is:{tot}')
avg=tot/len(nums)
print(f'the average is:{avg}')


the total is:75
the average is:15.0


# Write a program using loop to find the largest value


In [15]:

n = int(input("Enter number of values: "))

largest = int(input("Enter value 1: "))

for i in range(2, n + 1):
    num = int(input("Enter value " + str(i) + ": "))

    if num > largest:
        largest = num

print("Largest value =", largest)

Enter number of values: 2
Enter value 1: 3
Enter value 2: 4
Largest value = 4


In [33]:
import numpy as np


In [23]:
#converting list into numpy nd array
#list= can contain multiple datatype
#array= can contain only single datatype

marks= np.array([72.0,65.1,81,54,90])
print("Array:", marks)
print("Type:", type(marks))

Array: [72.  65.1 81.  54.  90. ]
Type: <class 'numpy.ndarray'>


In [26]:

marks= np.array([72,True,81,54,90])
print("Array:", marks)
print("Type:", type(marks))

Array: [72  1 81 54 90]
Type: <class 'numpy.ndarray'>


In [27]:

marks= np.array([72.0,'Hello',81,54,90])
print("Array:", marks)
print("Type:", type(marks))

Array: ['72.0' 'Hello' '81' '54' '90']
Type: <class 'numpy.ndarray'>


In [48]:
a0d= np.array(46)
print(f'Array{a0d}')
print("Type:", type(marks))

Array46
Type: <class 'numpy.ndarray'>


In [49]:
a0d = np.array(46)

print(f'Array{a0d}')
print(f'Type: {a0d.dtype}')
print(f'ndim: {a0d.ndim}')
print(f'shape:{a0d.shape}')
print(f'size: {a0d.size}')

Array46
Type: int64
ndim: 0
shape:()
size: 1


In [50]:
# two dimensional array

a2d = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Array: {a2d}')
print(f'Type: {a2d.dtype}')
print(f'ndim: {a2d.ndim}')
print(f'shape: {a2d.shape}')
print(f'size: {a2d.size}')

Array: [[1 2 3]
 [4 5 6]]
Type: int64
ndim: 2
shape: (2, 3)
size: 6


In [51]:
#three dimensional array
a3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(f'Array: {a3d}')
print(f'Type: {a3d.dtype}')
print(f'ndim: {a3d.ndim}')
print(f'shape: {a3d.shape}')
print(f'size: {a3d.size}')

Array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Type: int64
ndim: 3
shape: (2, 2, 3)
size: 12


#Create 3d array of shape 2,3,3. Check its dimension and shape by printing

In [52]:

a3d = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])

print("Array:")
print(a3d)

print("Dimension:", a3d.ndim)
print("Shape:", a3d.shape)


Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Dimension: 3
Shape: (2, 3, 3)


# INDEXING

In [55]:


a1d = np.array([10, 20, 30, 40, 50])

# to find first element in array
print(a1d[0])

# change the third element
a1d[2] = 23
print(a1d)

10
[10 20 23 40 50]


In [61]:
#to check the rows and columns of an array
a2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f'Array:\n{a2d}')

print(f'Row1, Col2: {a2d[0,1]}')

print(f'Row2, Col3: {a2d[1,2]}')

print(f'Row3, Col1: {a2d[2,0]}')

print(f'Second row: {a2d[1, :]}')

print(f'Second row: {a2d[1]}')

print(f'Second column: {a2d[:,1]}')

print(f'Third column: {a2d[:,2]}')

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row1, Col2: 2
Row2, Col3: 6
Row3, Col1: 7
Second row: [4 5 6]
Second row: [4 5 6]
Second column: [2 5 8]
Third column: [3 6 9]


In [62]:
print(f'Array:{a3d}')
print(f'row1, col2: {a3d[0,1,1]}')
print(f'row2, col3: {a3d[1,1,2]}')


Array:[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
row1, col2: 5
row2, col3: 15


#SLICING

In [64]:
print(f'First four elements: {a1d[:4]}')
print(f'First three elements: {a1d[:3]}')
print(f'Last three elements: {a1d[3:]}')
print(f'Last two elements: {a1d[2:]}')
print(f'Reverse: {a1d[::-1]}')
print(f'Middle:{a1d[2:6]}')
print(f'Every second  value: {a1d[::2]}')

First four elements: [10 20 23 40]
First three elements: [10 20 23]
Last three elements: [40 50]
Last two elements: [23 40 50]
Reverse: [50 40 23 20 10]
Middle:[23 40 50]
Every second  value: [10 23 50]


#Write a program to take 12 elements in an array and reverse only the first six values using slicing method

In [67]:

# take 12 elements in an array
a = np.array([int(input("Enter element: ")) for i in range(12)])

# reverse only the first six values
a[:6] = a[:6][::-1]

print("Array after reversing first six values:")
print(a)

Enter element: 4
Enter element: 2
Enter element: 1
Enter element: 4
Enter element: 6
Enter element: 3
Enter element: 2
Enter element: 1
Enter element: 6
Enter element: 3
Enter element: 2
Enter element: 8
Array after reversing first six values:
[3 6 4 1 2 4 2 1 6 3 2 8]


In [71]:

ze = np.zeros(5)
print(ze)
print(f'Type:{ze.dtype}')
print(f'ndim:{ze.ndim}')
print(f'shape:{ze.shape}')
print(f'size:{ze.size}')

[0. 0. 0. 0. 0.]
Type:float64
ndim:1
shape:(5,)
size:5


In [78]:
import numpy as np

ze = np.ones((2, 4), dtype=int)

print(ze)

print(f'Type: {ze.dtype}')
print(f'ndim: {ze.ndim}')
print(f'shape: {ze.shape}')
print(f'size: {ze.size}')

[[1 1 1 1]
 [1 1 1 1]]
Type: int64
ndim: 2
shape: (2, 4)
size: 8


In [75]:
full = np.full((2,3), 7)
print(full)
print(f'Type: {full.dtype}')
print(f'ndim: {full.ndim}')
print(f'shape: {full.shape}')
print(f'size: {full.size}')

[[7 7 7]
 [7 7 7]]
Type: int64
ndim: 2
shape: (2, 3)
size: 6


#Create a 4x2 matrix filled with 100

In [79]:

matrix = np.full((4, 2), 100)

print(matrix)

[[100 100]
 [100 100]
 [100 100]
 [100 100]]


#Generating sequence with arange() and linspace()

In [80]:
a= np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [83]:
#0 and 10 will be printed as first and last element and in between elements will come
b = np.linspace(0,10,6)
print(b)

[ 0.  2.  4.  6.  8. 10.]


#Random number generation

In [84]:
#values range does not change when random decimals are generated
print(f'Random decimal: {np.random.random(5)}')

Random decimal: [0.44148104 0.83736613 0.41540712 0.98235585 0.62475097]


In [93]:
#values range changes when random decimals are generated
print(f'Random Integer: {np.random.randint(5)}')

Random Integer: 3


In [96]:

print(f'Random Integer: {np.random.randint(1,11, size=(3,3))}')

Random Integer: [[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]


#Generate 10 random decimals